const nakanomiku = [
"**Go-Toubun no Hanayome** es conocido en inglés como **The Quintessential Quintuplets**.",
"El manga fue creado por Negi Haruba y se serializó en la revista Weekly Shōnen Magazine de Kodansha desde agosto de 2017 hasta febrero de 2020.",
"El anime de 'Go-Toubun no Hanayome' fue producido por el estudio de animación Tezuka Productions.",
"La primera temporada del anime se emitió en enero de 2019.",
"La segunda temporada del anime se estrenó en enero de 2021 y cubrió el arco de la historia de la Universidad.",
"El título japonés 'Go-Toubun no Hanayome' se traduce como 'La novia de los quintillizos'.",
"La serie sigue la historia de Fuutarou Uesugi, quien es contratado como tutor de las quintillizas Nakano: Ichika, Nino, Miku, Yotsuba e Itsuki.",
"El diseño de personajes del anime fue realizado por Michinosuke Nakamura.",
"El director de la primera temporada del anime fue Satoshi Kuwabara.",
"El director de la segunda temporada del anime fue Kaori.",
"La canción de apertura de la primera temporada se titula 'Gotōbun no Kimochi' interpretada por Nakanoke no Itsuzugo.",
"La canción de cierre de la primera temporada se titula 'Sign' interpretada por Aya Uchida.",
"La canción de apertura de la segunda temporada se titula 'Gotōbun no Katachi' interpretada por Nakano-ke no Itsutsugo.",
"La canción de cierre de la segunda temporada se titula 'Hatsukoi' interpretada por Nakanoke no Itsuzugo.",
"El manga de 'Go-Toubun no Hanayome' terminó con 14 volúmenes recopilatorios.",
"El autor del manga, Negi Haruba, reveló que el nombre de las quintillizas Nakano se inspiró en la serie 'Nogizaka Haruka no Himitsu'.",
"El apellido 'Nakano' de las quintillizas significa 'medio' o 'central' en japonés, lo que refleja su posición central en la vida de Fuutarou.",
"El anime de 'Go-Toubun no Hanayome' presenta diferentes colores de cabello para cada una de las quintillizas para ayudar a distinguirlas más fácilmente.",
"El personaje de Itsuki Nakano comparte su nombre con el famoso restaurante Itsuki, un lugar importante en la serie.",
"En el manga, el cumpleaños de las quintillizas Nakano se celebra el 5 de mayo, el día de los niños en Japón.",
"El manga de 'Go-Toubun no Hanayome' recibió una nominación al premio Taisho en 2019.",
"El anime de 'Go-Toubun no Hanayome' fue nominado a Mejor Anime en los Anime Awards de Crunchyroll en 2019.",
"El diseño de los personajes de 'Go-Toubun no Hanayome' se basa en los diseños originales de Negi Haruba, pero con algunas modificaciones para adaptarse al anime.",
"Negi Haruba, el autor del manga, reveló que la inspiración para la historia de 'Go-Toubun no Hanayome' provino de una experiencia personal.",
"El nombre de las quintillizas Nakano está basado en el orden en que nacieron: Ichika, Nino, Miku, Yotsuba e Itsuki.",
"En el manga, cada una de las quintillizas Nakano tiene un símbolo que las representa: una estrella para Ichika, un corazón para Nino, un círculo para Miku, una cruz para Yotsuba y un trébol para Itsuki.",
"El apellido 'Nakano' puede significar 'campo central' en japonés, lo que refleja la importancia de las quintillizas en la vida de Fuutarou.",
"El director de la primera temporada del anime, Satoshi Kuwabara, también trabajó en series como 'Dagashi Kashi' y 'Yu-Gi-Oh! Zexal'.",
"La serie de anime 'Go-Toubun no Hanayome' fue licenciada para su transmisión en inglés por Crunchyroll.",
"En el manga, la relación entre Fuutarou y las quintillizas Nakano se desarrolla gradualmente a lo largo de la historia, con momentos tanto cómicos como emocionales.",
"El manga de 'Go-Toubun no Hanayome' tuvo un spin-off titulado 'Go-Toubun no Hanayome: ∬'.",
"El spin-off de 'Go-Toubun no Hanayome' se centra en la vida escolar de las quintillizas antes de conocer a Fuutarou.",
"La trama de 'Go-Toubun no Hanayome' gira en torno a Fuutarou Uesugi, un estudiante de secundaria que se convierte en el tutor de las quintillizas Nakano.",
"El anime de 'Go-Toubun no Hanayome' adaptó fielmente la historia del manga, incluyendo eventos clave y momentos importantes de los personajes.",
"El manga de 'Go-Toubun no Hanayome' ganó el premio Kodansha Manga Award en 2019.",
"Negi Haruba, el autor del manga, reveló que el personaje de Fuutarou Uesugi se inspiró en sus propias experiencias como tutor privado.",
"El anime de 'Go-Toubun no Hanayome' recibió elogios por su animación fluida y su fiel adaptación del material de origen.",
"El manga de 'Go-Toubun no Hanayome' fue elogiado por su enfoque en el desarrollo de personajes y su equilibrio entre momentos cómicos y emotivos.",
"El diseño de personajes de 'Go-Toubun no Hanayome' fue elogiado por capturar las personalidades únicas de cada una de las quintillizas Nakano.",
"El manga de 'Go-Toubun no Hanayome' se publicó en la revista Weekly Shōnen Magazine, una de las revistas de manga más populares de Japón.",
"El director de la segunda temporada del anime, Kaori, también trabajó en series como 'Yuyushiki' y 'How to Keep a Mummy'.",
"La serie de anime 'Go-Toubun no Hanayome' fue dirigida por Satoshi Kuwabara y Kaori.",
"El manga de 'Go-Toubun no Hanayome' se destacó por su enfoque en el romance y la comedia, así como por su estilo artístico único.",
"El anime de 'Go-Toubun no Hanayome' fue bien recibido por los fanáticos y la crítica por su representación realista de las relaciones entre hermanas y su desarrollo de personajes.",
"El manga de 'Go-Toubun no Hanayome' tuvo varias adaptaciones al teatro, incluyendo una obra de teatro en vivo y una producción musical.",
"El anime de 'Go-Toubun no Hanayome' fue licenciado para su transmisión en inglés por Crunchyroll y Funimation.",
"La serie de anime 'Go-Toubun no Hanayome' recibió una adaptación cinematográfica que se estrenó en 2022.",
"La película de 'Go-Toubun no Hanayome' adaptó el arco final del manga y sirvió como conclusión de la historia.",
"El manga de 'Go-Toubun no Hanayome' fue elogiado por su trama bien estructurada y su conclusión satisfactoria.",
"El anime de 'Go-Toubun no Hanayome' fue nominado a varios premios en los Crunchyroll Anime Awards, incluyendo Mejor Anime del Año y Mejor Comedia.",
"El manga de 'Go-Toubun no Hanayome' vendió más de 10 millones de copias en todo el mundo.",
"Negi Haruba, el autor del manga, ha expresado su aprecio por el amor y el apoyo de los fanáticos de 'Go-Toubun no Hanayome' en numerosas ocasiones.",
"El anime de 'Go-Toubun no Hanayome' fue bien recibido por su representación realista de las luchas de la vida escolar y el crecimiento personal.",
"El éxito de 'Go-Toubun no Hanayome' inspiró una variedad de mercancías, incluyendo figuras de acción, productos de papelería y CD de banda sonora.",
"Aunque las quintillizas Nakano comparten rasgos similares, tienen personalidades distintas que se desarrollan a lo largo de la serie.",
"El anime de 'Go-Toubun no Hanayome' aborda temas de amistad, familia y romance de una manera conmovedora y atractiva para los espectadores."
];

function getRandomNakanoMikuMessage() {
    const randomIndex = Math.floor(Math.random() * nakanomiku.length);
    return nakanomiku[randomIndex];
}

module.exports = {
    getRandomNakanoMikuMessage
};
