const asupan = [
    "El 16% de las mujeres nacen rubias, y 33% de las mujeres son rubias.",
    "El sol libera más energía en un segundo que toda la energía consumida por la humanidad desde su inicio.",
    "Napoleón Bonaparte calculó que las piedras de las pirámides de Egipto serían suficientes para construir un muro alrededor de Francia.",
    "La letra 'J' es la única letra que no aparece en la tabla periódica.",
    "Una persona parpadea aproximadamente 25 mil veces por semana.",
    "El elefante es el único animal con 4 rodillas.",
    "El material más resistente creado por la naturaleza es la tela de araña.",
    "Los rusos atienden el teléfono diciendo 'Estoy oyendo'.",
    "La hija de Shakespeare era analfabeta.",
    "Einstein nunca fue un buen alumno, y ni siquiera hablaba bien a los 9 años, sus padres creían que era retrasado mental.",
    "Los CDs fueron diseñados para recibir 72 minutos de música porque esa es la duración de la Novena Sinfonía de Beethoven.",
    "Las caricaturas del Pato Donald fueron vetadas en Finlandia porque éste no usaba pantalón.",
    "Un kilo de papas fritas cuesta 200 veces lo que vale un kilo de patatas.",
    "En la ciudad de Los Ángeles hay más automóviles que gente.",
    "El nombre más común del mundo es Mohammed.",
    "Los perezosos pueden aguantar más tiempo el aliento que los delfines.",
    "Los Froot Loops son todos del mismo sabor.",
    "Las manzanas en el supermercado pueden tener hasta un año.",
    "Los pulpos tienen 3 corazones.",
    "En las Filipinas, McDonald's vende spaghetti.",
    "Hitler fue nominado a un Nobel de la Paz.",
    "Las langostas saborean con los pies.",
    "El Empire State tiene su propio código postal.",
    "Las sombras son más oscuras en la luna.",
    "La Estatua de la Libertad solía ser un faro.",
    "Las ManhattAnts son una especie de hormigas únicas de Nueva York.",
    "Los tanques británicos están equipados para hacer té.",
    "Los aguacates son una fruta, no una verdura. Técnicamente se consideran una baya de una sola semilla.",
    "La Torre Eiffel puede ser 15 cm más alta durante el verano. Se debe a la expansión térmica.",
    "La tripofobia es el miedo a los agujeros muy juntos.",
    "Australia es más ancha que la Luna. La Luna tiene 3400 km de diámetro, mientras que el diámetro de Australia es de casi 4000 km.",
    "'Melifluo' es un sonido que resulta agradablemente suave y musical al escucharlo.",
    "Las Spice Girls se llamaban originalmente Touch.",
    "Los dientes humanos son la única parte del cuerpo que no puede curarse por sí misma.",
    "En Suiza es ilegal tener una sola cobaya.",
    "Los antiguos romanos solían echar un trozo de pan tostado en el vino para tener buena salud, de ahí que brindemos.",
    "El corazón de las gambas se encuentra en la cabeza.",
    "Amy Poehler sólo tenía siete años más que Rachel McAdams cuando asumió el papel de mamá guay en Chicas malas.",
    "La gente es más creativa en la ducha.",
    "Los conejos bebé se llaman gazapos.",
    "El unicornio es el animal nacional de Escocia.",
    "El primer avión voló el 17 de diciembre de 1903.",
    "Venus es el único planeta que gira en el sentido de las agujas del reloj.",
    "La nuez moscada es un alucinógeno.",
    "Las artes solían ser un deporte olímpico.",
    "El gorro de cocinero tiene 100 pliegues.",
    "En 2014, hubo un 'match' de Tinder en la Antártida.",
    "El himno nacional español no tiene letra.",
    "La palabra japonesa 'Kuchi zamishi' es el acto de comer cuando no se tiene hambre porque la boca se siente sola.",
    "La probabilidad de que exista una langosta azul es de una entre dos millones.",
    "Sólo hay una letra que no aparece en el nombre de ningún estado americano: la Q.",
    "Las icónicas suelas rojas de los zapatos Louboutin se inspiraron en Andy Warhol.",
    "El libro 'A la recherche du temps perdu', de Marcel Proust, contiene unos 9.609.000 caracteres, lo que lo convierte en el libro más largo del mundo.",
    "Google Images se creó después de que Jennifer López llevara ese famoso vestido en los Grammy del año 2000.",
    "El reloj del Big Ben se detuvo a las 22:07 horas del 27 de mayo de 2005.",
    "Walt Disney es actualmente el que más premios de la Academia tiene.",
    "Hay una fruta que sabe a budín de chocolate: el zapote negro.",
    "La Reina Isabel II tenía formación en mecánica.",
    "Las cabezas de la Isla de Pascua tienen cuerpo.",
    "Las palomas pueden distinguir entre Picasso y Monet.",
    "Los actores que ponen voz a Mickey y Minnie se han casado en la vida real.",
    "El ojo humano puede distinguir alrededor de 10 millones de colores.",
    "La miel nunca se echa a perder. Se han encontrado frascos de miel de hace miles de años en tumbas egipcias y aún son comestibles.",
    "El cerebro humano tiene aproximadamente 86 mil millones de neuronas.",
    "La Gran Muralla China no es visible desde el espacio a simple vista.",
    "El Monte Everest crece aproximadamente 4 milímetros al año debido al movimiento tectónico.",
    "El ser humano comparte aproximadamente el 60% de su ADN con los plátanos.",
    "El corazón de una ballena azul es tan grande que un ser humano podría nadar a través de sus arterias.",
    "Un rayo puede alcanzar temperaturas de aproximadamente 30,000 grados Celsius, cinco veces más caliente que la superficie del sol.",
    "El tiburón de Groenlandia puede vivir hasta 400 años, siendo uno de los vertebrados más longevos.",
    "El agua caliente se congela más rápido que el agua fría en ciertas condiciones, un fenómeno conocido como efecto Mpemba.",
    "Las mariposas tienen sensores de sabor en sus pies para encontrar plantas adecuadas donde poner sus huevos.",
    "El cerebro de un pulpo está distribuido en sus tentáculos, lo que le permite realizar tareas complejas con cada uno de ellos.",
    "El Koala tiene huellas dactilares muy similares a las humanas, lo que puede confundir a los investigadores en escenas de crimen.",
    "El pez luna puede poner hasta 300 millones de huevos a la vez.",
    "Las hormigas no duermen. Sin embargo, tienen ciclos de reposo cortos.",
    "El agua constituye aproximadamente el 70% del cuerpo humano.",
    "El sonido viaja 4.3 veces más rápido en el agua que en el aire.",
    "La Tierra recibe más energía del sol en una hora que toda la energía consumida por la humanidad en un año.",
    "La luz del sol tarda aproximadamente 8 minutos y 20 segundos en llegar a la Tierra.",
    "La Torre Eiffel fue construida para ser una estructura temporal para la Exposición Universal de 1889.",
    "El primer teléfono móvil pesaba 1.1 kilogramos y tenía una duración de batería de 30 minutos en conversación.",
    "El dragón de Komodo tiene una mordedura venenosa que puede causar la muerte por envenenamiento y pérdida de sangre.",
    "Las estrellas de mar pueden regenerar partes perdidas de su cuerpo, incluso brazos completos.",
    "El primer ser vivo enviado al espacio fue una mosca de la fruta en 1947.",
    "El planeta más caliente en el sistema solar es Venus, con temperaturas que alcanzan los 462 grados Celsius.",
    "Las ballenas jorobadas son conocidas por sus complejas canciones que pueden durar hasta 20 minutos y se repiten durante horas.",
    "El tigre es el felino más grande del mundo, pudiendo alcanzar hasta 3.3 metros de longitud y pesar más de 300 kilogramos.",
    "La ciudad de Venecia en Italia se compone de 118 pequeñas islas conectadas por más de 400 puentes.",
    "La primera calculadora mecánica fue inventada por Blaise Pascal en 1642.",
    "El oro es comestible y se utiliza en pequeñas cantidades para decorar alimentos gourmet y bebidas.",
    "El músculo más fuerte en relación a su tamaño en el cuerpo humano es el masetero, que se encuentra en la mandíbula.",
    "El colibrí es el único ave que puede volar hacia atrás.",
    "El pez globo contiene una toxina mortal que es 1,200 veces más venenosa que el cianuro.",
    "La luna se está alejando de la Tierra a un ritmo de aproximadamente 3.8 centímetros por año.",
    "El bambú puede crecer hasta 91 centímetros en un solo día.",
    "El cerebro humano es más activo durante la noche que durante el día.",
    "El veneno de la medusa avispa de mar es uno de los más mortales del mundo y puede matar a una persona en minutos.",
    "El kiwi es el único ave sin alas que pone huevos proporcionalmente grandes para su tamaño.",
    "El fósforo fue descubierto por accidente en 1669 por el alquimista alemán Hennig Brand.",
    "La biblioteca más grande del mundo es la Biblioteca del Congreso en Washington, D.C., con más de 170 millones de ítems.",
    "El nombre 'Canadá' proviene de la palabra iroquesa 'kanata', que significa 'aldea' o 'asentamiento'."
];

function getRandomMessage() {
    const randomIndex = Math.floor(Math.random() * asupan.length);
    return asupan[randomIndex];
}

module.exports = {
    getRandomMessage
};
